import { ClaimRecord } from './types';

export const HOTLINKED_ASSETS = {
  claimerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAglTHzYqsugz1ADnYwYPPoPlIuD7HeTNwoCGN90BVZI_PJmfLewU4BPGmVDGfkriJpO8kr0iXXTGc2Gm6MRDWMc_dG8moRQQUzFsUTnL8jx9nq50WK7KApRo6kGZHBuXFTgEzYBRV0Y1Six6RQRE3T5yDL4ExbE1yNkOztod6Teqn-rreKrm5GMuNQM2zD1iKcQrftWTWU_2egHuZwdkJ_j4m9_w9P8qr6HK7iXfVVMH6i3NECqCqTCQ',
  validatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCGEo0uBU0QJl9bJDkaUJEFYa0NY79yShKsyYgTYW4wIWGiIg2k0wj5Jl1yx8R6GF2uyxYW0BrYXSNgvzTAy95UiWwk9lIfXiEm9KzY2viylx7gbmhQamtkvOmK7V_lIBaIguLDF_ai80jqormUidtTFCa57LYVg2g9UQ3p66Rpu_0KYCAJrUb9Xz81seUO8cuqNpbUbf2i7IglgxR1oj6zwZkAnjYP18Q-zMLO9kCK9oqzwwXQMgedyw',
  documentBillImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_cSvgSsjGviJm2FQTbNB_95Bll4Gbopin4P2wBFilP8SyPM1yE9OgkbFHlvleyY8GoPZAhN6IuU9yfpCLWucg70RDBD7n9AZ50SfRy-rOTwUAidnUmTho8mAAZWyPlLBlHAECIZ5MAMGnotpJN6xqMSx1RciZXx5hlaHJltZSESlBVcRDSLQj85y0Z8jndXWshtdplVLBRVrKu2__QoaAedeZzppcaAow2JCRoO92oNKzKgPOeWED0A',
  thumbnailBill1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3Lakk67o4Ki1CULrjaj7W-6W1Ip73bLms23PjPjQvGTkSf4NnQyATdIb8sq7Ki6FQO4AzKHPiO_Qsz-g6AUO2B11kvBawUM8W106qXTfZXpSmKpL-GKpH9OIVk9kIlIi3LjG6hBEAWAPd_DjK2M184aGcBz3R9rjKQhPqYFDPCjhdhsKeVKrzCCsUSK_KR8xe-B_oT0EHkaw2vFpoVvaHzdDEQQnTaeuIEeYO_vYKqYtr3PNypRBxVQ',
  thumbnailSummary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBW_m9bhab8lHcTMT7iX4Umn-nzS_fykNfaewn4Tu9IJq7waGBxSrCoGC5zBr2ojIYdwy8sSs9sh2iXh1WRczY58jH86vTTavRefR4t-mNRg6utG7x1EOrXVi7gVivKoY0y16sn7IXMdXUTTzNoE-dyR6J3mBydQKGlnuvoV75AJXs0PRGUkb3QQkCNkrHtNP6vBuo4Smo7iv3_bhdhIvCtN09z1OcR8_m6l9_SMTtDliWDPhK7aNvs1g',
  carFrontDamage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
};

export const INITIAL_CLAIMS: ClaimRecord[] = [
  {
    id: '#CLM-8921',
    claimerName: 'Eleanor Vance',
    carPolicy: 'POL-2023-A491',
    submissionDate: 'Oct 24, 2023',
    incidentDate: 'Oct 22, 2023, 14:30 PM',
    incidentLocation: 'Intersection of 5th Ave & Main St, Seattle, WA',
    vehicle: '2021 Toyota Camry SE',
    vin: '4T1B11HK5MU123XXX',
    repairEstimate: 4250.00,
    deductible: 500.00,
    potentialPayout: 3750.00,
    docsUploaded: 6,
    docsTotal: 6,
    status: 'pending',
    statusLabel: 'Pending',
    diagnosisCode: 'J01.90 (Collision / Bumper Deformation)',
    aiSummary: {
      damageAssessment: 'Moderate Frontal Impact',
      damageVerified: true,
      policyMatching: 'Fully Covered',
      policyActive: true,
      fraudScore: 12,
      fraudLabel: 'Low Risk (12/100)',
    },
    financialBreakdown: {
      originalEstimate: 4250.00,
      deductible: 500.00,
      consumables: 0.00,
      approvedAmount: 3750.00,
    },
    validatorRemarks: 'Awaiting primary inspection sign-off and garage quote validation.',
    expectedPayoutDate: 'Nov 02, 2023',
    documents: [
      {
        id: 'doc-1',
        title: 'Front_Bumper_Damage.jpg',
        category: 'Car Photos',
        size: '2.4 MB',
        required: true,
        status: 'verified_agent',
        fileName: 'Front_Bumper_Damage.jpg',
        fileSize: '2.4 MB',
        iconName: 'image',
        imageUrl: HOTLINKED_ASSETS.thumbnailBill1,
      },
      {
        id: 'doc-2',
        title: 'Police_Report_SPD.pdf',
        category: 'Police Report',
        size: '1.1 MB',
        required: true,
        status: 'verification_failed',
        fileName: 'Police_Report_SPD.pdf',
        fileSize: '1.1 MB',
        error: 'Missing badge signature in section 4',
        iconName: 'description',
        imageUrl: HOTLINKED_ASSETS.thumbnailSummary,
      },
      {
        id: 'doc-3',
        title: 'Driver_License.jpg',
        category: 'Driving License',
        size: '0.8 MB',
        required: true,
        status: 'verified_agent',
        fileName: 'Driver_License.jpg',
        fileSize: '0.8 MB',
        iconName: 'badge',
        imageUrl: HOTLINKED_ASSETS.thumbnailBill1,
      },
      {
        id: 'doc-4',
        title: 'AutoBody_Estimate.pdf',
        category: 'Repair Estimate',
        size: '3.2 MB',
        required: true,
        status: 'verification_failed',
        fileName: 'AutoBody_Estimate.pdf',
        fileSize: '3.2 MB',
        error: 'Tax invoice mismatch with certified garage rate',
        iconName: 'request_quote',
        imageUrl: HOTLINKED_ASSETS.documentBillImage,
      },
    ],
  },
  {
    id: '#CLM-8920',
    claimerName: 'Marcus Sterling',
    carPolicy: 'POL-2022-B112',
    submissionDate: 'Oct 23, 2023',
    incidentDate: 'Oct 21, 2023, 09:15 AM',
    incidentLocation: 'I-5 Southbound Milepost 165',
    vehicle: '2019 Honda Civic Sport',
    vin: '2HGFC2F79KH542XXX',
    repairEstimate: 1120.50,
    deductible: 200.00,
    potentialPayout: 920.50,
    docsUploaded: 3,
    docsTotal: 3,
    status: 'succeeded',
    statusLabel: 'Succeeded',
    aiSummary: {
      damageAssessment: 'Minor Rear Scratch & Light Dent',
      damageVerified: true,
      policyMatching: 'Standard Coverage',
      policyActive: true,
      fraudScore: 6,
      fraudLabel: 'Minimal Risk (6/100)',
    },
    financialBreakdown: {
      originalEstimate: 1120.50,
      deductible: 200.00,
      consumables: 0.00,
      approvedAmount: 920.50,
    },
    validatorRemarks: 'Claim approved under express fast-track processing.',
    expectedPayoutDate: 'Oct 26, 2023',
    documents: [],
  },
  {
    id: '#CLM-8915',
    claimerName: 'Sarah Jenkins',
    carPolicy: 'POL-2021-C998',
    submissionDate: 'Oct 21, 2023',
    incidentDate: 'Oct 19, 2023, 22:45 PM',
    incidentLocation: 'Pine Street Parking Garage, Floor 3',
    vehicle: '2022 Hyundai Tucson',
    vin: 'KM8J33A41NU789XXX',
    repairEstimate: 8500.00,
    deductible: 500.00,
    potentialPayout: 8000.00,
    docsUploaded: 2,
    docsTotal: 4,
    status: 'rejected',
    statusLabel: 'Rejected',
    aiSummary: {
      damageAssessment: 'Severe Unreported Structural Damage',
      damageVerified: false,
      policyMatching: 'Excluded Peril',
      policyActive: true,
      fraudScore: 78,
      fraudLabel: 'High Risk (78/100)',
    },
    financialBreakdown: {
      originalEstimate: 8500.00,
      deductible: 500.00,
      consumables: 0.00,
      approvedAmount: 0.00,
    },
    validatorRemarks: 'Pre-existing mechanical failure prior to incident. Claim rejected under policy section 7.2.',
    documents: [],
  },
  {
    id: '#CLM-8924',
    claimerName: 'David Chen',
    carPolicy: 'POL-2023-F221',
    submissionDate: 'Oct 24, 2023',
    incidentDate: 'Oct 23, 2023, 11:00 AM',
    incidentLocation: 'Bellevue Square Mall Lot B',
    vehicle: '2023 Tesla Model Y',
    vin: '7SAYGDEE1PF982XXX',
    repairEstimate: 340.00,
    deductible: 100.00,
    potentialPayout: 240.00,
    docsUploaded: 1,
    docsTotal: 1,
    status: 'pending',
    statusLabel: 'Pending',
    aiSummary: {
      damageAssessment: 'Windshield Chip & Glass Seal',
      damageVerified: true,
      policyMatching: 'Glass Endorsement Active',
      policyActive: true,
      fraudScore: 4,
      fraudLabel: 'Low Risk (4/100)',
    },
    financialBreakdown: {
      originalEstimate: 340.00,
      deductible: 100.00,
      consumables: 0.00,
      approvedAmount: 240.00,
    },
    documents: [],
  },
  {
    id: '#CLM-2024-089',
    claimerName: 'Jane Doe',
    carPolicy: 'POL-882',
    submissionDate: 'Oct 12, 2024',
    incidentDate: 'Oct 11, 2024, 16:20 PM',
    incidentLocation: 'Roosevelt Way & 45th St, Seattle, WA',
    vehicle: '2020 Toyota Camry',
    vin: '4T1B11HK2LU889YYY',
    repairEstimate: 1250.00,
    deductible: 150.00,
    potentialPayout: 1050.00,
    docsUploaded: 6,
    docsTotal: 6,
    status: 'approved',
    statusLabel: 'Approved',
    aiSummary: {
      damageAssessment: 'Left Fender & Headlamp Housing',
      damageVerified: true,
      policyMatching: 'Comprehensive Gold',
      policyActive: true,
      fraudScore: 8,
      fraudLabel: 'Low Risk (8/100)',
    },
    financialBreakdown: {
      originalEstimate: 1250.00,
      deductible: 150.00,
      consumables: 50.00,
      approvedAmount: 1050.00,
    },
    validatorRemarks: 'Documents verified against policy POL-882. Vehicle inspection and collision report align with incident details. Standard deductible applied as per section 4.1. Consumables excluded from coverage.',
    expectedPayoutDate: 'Oct 20, 2024',
    documents: [],
  }
];

export const INITIAL_UPLOAD_SLOTS = [
  {
    id: 'slot-1',
    title: 'Car Photos (All Angles)',
    subtitle: 'Required',
    required: true,
    icon: 'directions_car',
    categoryPayload: 'car pics',
    status: 'error' as const,
    fileName: 'car_front_damage.jpg',
    error: 'Car photo is too dark or VIN number not visible. Please re-upload a clear, well-lit photo showing damage and vehicle stamp.',
    borderTheme: 'error' as const,
    hint: 'PDF, JPG, PNG up to 10MB'
  },
  {
    id: 'slot-2',
    title: 'Police FIR / Accident Report',
    subtitle: 'Required',
    required: true,
    icon: 'local_police',
    categoryPayload: 'police report',
    status: 'empty' as const,
    borderTheme: 'warning' as const,
    hint: 'PDF, JPG, PNG up to 10MB'
  },
  {
    id: 'slot-3',
    title: 'Driving License & RC Copy',
    subtitle: 'Required',
    required: true,
    icon: 'id_card',
    categoryPayload: 'driving license',
    status: 'empty' as const,
    borderTheme: 'warning' as const,
    hint: 'Click to upload or drag & drop'
  },
  {
    id: 'slot-4',
    title: 'Repair Estimate from Garage',
    subtitle: 'Required',
    required: true,
    icon: 'handyman',
    categoryPayload: 'repair estimate',
    status: 'empty' as const,
    borderTheme: 'warning' as const,
    hint: 'Click to upload or drag & drop'
  },
  {
    id: 'slot-5',
    title: 'Third-Party Details (if any)',
    subtitle: 'Optional',
    required: false,
    icon: 'group',
    categoryPayload: 'third party',
    status: 'empty' as const,
    borderTheme: 'success' as const,
    hint: 'Click to upload or drag & drop'
  },
  {
    id: 'slot-6',
    title: 'Payment Receipt for Towing',
    subtitle: 'Optional',
    required: false,
    icon: 'receipt_long',
    categoryPayload: 'towing receipt',
    status: 'empty' as const,
    borderTheme: 'success' as const,
    hint: 'Click to upload or drag & drop'
  }
];
